title: YORABA
description: Your Software Engineering Hub
show_downloads: false
google_analytics: G-T8BWX5RG3W
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  tools:
    output: true
  cheatsheets:
    output: true

defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "cheatsheets"
    values:
      layout: "post"
