#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --checks html --checks sri --ignore-urls '/fonts.gstatic.com/'
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-cayman.gemspec
